---
title: Assignments
output:
  html_document:
    toc: true
    toc_float: true
---

# Labs
#### 16% of your overall grade
#### 40 points total; 10 points each

You are encouraged to work in partners or teams of up to 4 people on labs.
However, should you choose to work in teams, labs **must** be submitted as a
shared GitHub repository. I will evaluate the commits made by team members
before assigning final points. Each team member should upload a link to the
corresponding repo on canvas.

|**Lab** | **Topic**                           | **Assigned** | **Due** | 
|:------:| :-----------------------------------| :-----------:| :------:| 
| 1      | [Iterations with Base R](lab1.html) | 4/8/20       | 4/15/20 |
| 2      | Iterations with {purrr}             | 4/15/20      | 4/22/20 |
| 3      | Writing Functions 1                 | 5/6/20       | 5/13/20 |
| 4      | Writing Functions 2                 | 5/20/20      | 5/27/20 |

# Midterm
#### 24% of your overall grade
#### 60 points total

**Assigned**: 4/20/20 & 4/22/20

**Due**: 5/4/20

Two parts: 

* Small in-class worksheet to demonstrate knowledge (4/22/20; 10 points)
  + Identifying bugs in code
  + Multiple choice/fill-in the blank questions
  + Free response
  
* Take-home portion to demonstrate ability to write the correct code (assigned 4/20/20; 50 points)
  + Write loops to solve problems

# Final Project
#### 60% of your overall grade
#### 150 points total

|**Component**     | **Points**| **Due** | 
|:-----------------|:----------|:--------| 
| Groups Finalized | 0         |  4/8/20|
| [Outline](https://uo-datasci-specialization.github.io/c3-fun_program2020/site-syllabus.html#outline_(10_points;_5%))  | 10 | 4/29/20 | 
| [Draft](https://uo-datasci-specialization.github.io/c3-fun_program2020/site-syllabus.html#draft_data_preparation_script_(20_points)) |  20 | 5/25/20 | 
| [Peer review](https://uo-datasci-specialization.github.io/c3-fun_program2020/site-syllabus.html#peer_review_of_data_preparation_script_(20_points)) | 20 | 6/1/20 | 
| [Product](https://uo-datasci-specialization.github.io/c3-fun_program2020/site-syllabus.html#final_product_grading_(100_points)) |  100 | 6/10/20 (11:59 pm) | 



